// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ybizlulzpvgyhnlzkmqm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InliaXpsdWx6cHZneWhubHprbXFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNDc0MTYsImV4cCI6MjA2ODgyMzQxNn0.7ST05id6DCtATPsf0Xfx310YyT4bOCMkffqIi4w2pAs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});